designsafe/apps/djangoRT/urls.py
from django.conf.urls import url

from designsafe.apps.djangoRT import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new-ticket/$', views.ticketcreate, name='ticketcreate'),
    # url(r'^new-ticket/guest/$', views.ticketcreateguest, name='ticketcreateguest'),
    url(r'^tickets/$', views.mytickets, name='mytickets'),
    url(r'^tickets/(?P<ticketId>\d+)/$', views.ticketdetail, name='ticketdetail'),
    url(r'^tickets/(?P<ticketId>\d+)/reply/$', views.ticketreply, name='ticketreply'),
    url(r'^tickets/(?P<ticketId>\d+)/close/$', views.ticketclose, name='ticketclose'),
    url(r'^tickets/(?P<ticketId>\d+)/attachment/(?P<attachmentId>\d+)/$', views.ticketattachment, name='ticketattachment'),
]

designsafe/urls.py
"""
DesignSafe-CI URL Configuration
===============================

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/

Examples:
---------

**Function views**

#. Add an import:  from my_app import views
#. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')

**Class-based views**

#. Add an import:  from other_app.views import Home
#. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
    
**Including another URLconf**

#. Add an import:  from blog import urls as blog_urls
#. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from designsafe.apps.auth.views import login_options as des_login_options
from django.contrib.auth.views import logout as des_logout
from designsafe.views import project_version as des_version

# sitemap - classes must be imported and added to sitemap dictionary
from django.contrib.sitemaps.views import sitemap
from cms.sitemaps import CMSSitemap
from designsafe.sitemaps import StaticViewSitemap, DynamicViewSitemap, HomeSitemap, ProjectSitemap, SubSitemap
from designsafe import views

# cms preferences
CMSSitemap.priority = 0.7
CMSSitemap.changefreq = 'weekly'

sitemaps = {
    'home': HomeSitemap,
    'subsite': SubSitemap,
    'static': StaticViewSitemap,
    'dynamic': DynamicViewSitemap,
    'projects': ProjectSitemap,
    'cmspages': CMSSitemap,
}

urlpatterns = [
    # admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/impersonate/', include('impersonate.urls')),

    # sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # terms-and-conditions
    url(r'^terms/', include('termsandconditions.urls')),

    url(r'^api/', include('designsafe.apps.api.urls', namespace='designsafe_api')),

    # RAMP verification
    url(r'{}.html$'.format(settings.RAMP_VERIFICATION_ID), TemplateView.as_view(template_name='ramp_verification.html')),
    
    # api urls, just for the samples.
    url(r'^applications/', include('designsafe.apps.applications.urls',
                                namespace='designsafe_applications')),
    url(r'^data/', include('designsafe.apps.data.urls', namespace='designsafe_data')),
    url(r'^rw/workspace/', include('designsafe.apps.workspace.urls',
                                   namespace='designsafe_workspace')),
    url(r'^notifications/', include('designsafe.apps.notifications.urls',
                                    namespace='designsafe_notifications')),
    url(r'^search/', include('designsafe.apps.search.urls',
                                    namespace='designsafe_search')),
    url(r'^geo/', include('designsafe.apps.geo.urls',
                                    namespace='designsafe_geo')),
    url(r'^recon-portal/', include('designsafe.apps.rapid.urls',
                                    namespace='designsafe_rapid')),


    # auth
    url(r'^account/', include('designsafe.apps.accounts.urls',
        namespace='designsafe_accounts')),
    url(r'^register/$', RedirectView.as_view(
        pattern_name='designsafe_accounts:register', permanent=True), name='register'),

    # dashboard
    url(r'^dashboard/', include('designsafe.apps.dashboard.urls',
        namespace='designsafe_dashboard')),

    # need a fancier redirect here to pass the code param along
    url(r'^activate/(?:(?P<code>.+)/)?$',
        lambda x, code: HttpResponseRedirect(
            reverse('designsafe_accounts:email_confirmation',
                    args=[code] if code else None)
        )),
    url(r'^password-reset/(?:(?P<code>.+)/)?$',
        lambda x, code: HttpResponseRedirect(
            reverse('designsafe_accounts:password_reset',
                    args=[code] if code else None)
        )),

    # box
    url(r'^account/applications/box/', include('designsafe.apps.box_integration.urls',
        namespace='box_integration')),

    # dropbox
    url(r'^account/applications/dropbox/', include('designsafe.apps.dropbox_integration.urls',
        namespace='dropbox_integration')),

    # googledrive
    url(r'^account/applications/googledrive/', include('designsafe.apps.googledrive_integration.urls',
        namespace='googledrive_integration')),

    # google site verification
    url(r'{}.html$'.format(settings.GOOGLE_SITE_VERIFICATION_ID), TemplateView.as_view(template_name='google_verification.html')),

    # auth
    url(r'^auth/', include('designsafe.apps.auth.urls', namespace='designsafe_auth')),

    url(r'^login/$', des_login_options, name='login'),
    url(r'^logout/$', des_logout,
        {'next_page': '/auth/logged-out/'}, name='logout'),

    # help
    url(r'^help/', include('designsafe.apps.djangoRT.urls', namespace='djangoRT')),

    # webhooks
    url(r'^webhooks/', include('designsafe.webhooks')),

    # version check
    url(r'^version/', des_version),

    # cms handles everything else
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),

]
if settings.DEBUG: 
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

designsafe/apps/djangoRT/forms.py
from django import forms
from django.conf import settings
from django.core.validators import validate_email
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget


class MultiEmailField(forms.Field):
    """
    This was pulled from : https://docs.djangoproject.com/en/1.7/ref/forms/validation/
    """

    def to_python(self, value):
        """ Normalize data to a list of strings. """

        # Return an empty list if no input was given.
        if not value:
            return []
        return value.split(',')

    def validate(self, value):
        """ Check if value consists only of valid emails. """

        # Use the parent's handling of required fields, etc.
        super(MultiEmailField, self).validate(value)

        for email in value:
            validate_email(email.strip())


class BaseTicketForm(forms.Form):
    """
    Base form class for Tickets.
    """
    first_name = forms.CharField(widget=forms.TextInput(), max_length=255, required=True)
    last_name = forms.CharField(widget=forms.TextInput(), max_length=255, required=True)
    email = forms.EmailField(widget=forms.EmailInput(), required=True)
    subject = forms.CharField(widget=forms.TextInput(), max_length=255, required=True)

    category_choices = (('', 'Choose one'),) + settings.TICKET_CATEGORIES
    category = forms.CharField(widget=forms.Select(choices=category_choices),
                               required=True)
    problem_description = forms.CharField(widget=forms.Textarea(), required=True)
    attachment = forms.FileField(required=False)

    error_page = forms.CharField(widget=forms.HiddenInput(), required=False)
    http_referer = forms.CharField(widget=forms.HiddenInput(), required=False)


class TicketForm(BaseTicketForm):
    """
    Authenticated users ticket form. Additional "CC" field. This field is not
    provided to anonymous users because it could be used for spam.
    """
    cc = MultiEmailField(widget=forms.TextInput(), label='CC', required=False,
                         help_text='You can copy other people on this ticket. '
                                   'Multiple emails should be comma-separated')

class TicketGuestForm(BaseTicketForm):
    """
    Anonymous users ticket form. Adds a CAPTCHA to reduce spam submissions.
    """
    captcha = ReCaptchaField(widget=ReCaptchaWidget)
    pass

class ReplyForm(forms.Form):
    """
    Ticket Reply form.
    """
    reply = forms.CharField(required=True, widget=forms.Textarea(), label="Enter Reply")
    attachment = forms.FileField(required=False)

class CloseForm(forms.Form):
    """
    Ticket Close form.
    """
    reply = forms.CharField(required=True, widget=forms.Textarea(), label="Enter Close Comment")

designsafe/apps/djangoRT/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from designsafe.apps.djangoRT import rtUtil, forms, rtModels
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
import logging
import mimetypes
import pytz

logger = logging.getLogger(__name__)


def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('djangoRT:mytickets'))
    return HttpResponseRedirect(reverse('djangoRT:ticketcreate'))

@login_required
def mytickets(request):
    rt = rtUtil.DjangoRt()
    show_resolved = 'show_resolved' in request.GET
    fmt = request.GET.get('fmt', 'html')

    tickets = rt.getUserTickets(request.user.email, show_resolved=show_resolved)
    context = {
        'tickets': tickets,
        'show_resolved': show_resolved
    }
    if fmt == 'json':
        return JsonResponse(tickets, safe=False)
    else:
        return render(request, 'djangoRT/ticketList.html', context)

@login_required
def ticketdetail(request, ticketId):
    rt = rtUtil.DjangoRt()

    if not rt.hasAccess(ticketId, request.user.email):
        raise PermissionDenied

    ticket = rt.getTicket(ticketId)
    ticket_history = rt.getTicketHistory(ticketId)

    for history in ticket_history:
        # remove bogus "untitled" attachments
        history['Attachments'] = filter(lambda a: not a[1].startswith('untitled ('),
                                        history['Attachments'])

    return render(request, 'djangoRT/ticketDetail.html', {
        'ticket': ticket,
        'ticket_history': ticket_history,
        'ticket_id': ticketId
    })


def ticketcreate(request):

    template_name = 'djangoRT/ticketCreate.html'
    if request.user.is_authenticated:
        form_cls = forms.TicketForm
    else:
        form_cls = forms.TicketGuestForm

    if request.method == 'POST':
        form = form_cls(request.POST, request.FILES)

        if form.is_valid():
            requestor_meta = '%s %s <%s>' % (
                form.cleaned_data['first_name'],
                form.cleaned_data['last_name'],
                form.cleaned_data['email'])

            meta = (
                ('Opened by', request.user),
                ('Category', dict(settings.TICKET_CATEGORIES)[form.cleaned_data['category']]),
                ('Resource', 'DesignSafe'),
            )
            if form.cleaned_data['error_page'] is not None:
                meta += (
                    ('Error Page', form.cleaned_data['error_page']),
                    ('HTTP Referer', form.cleaned_data['http_referer']),
                )

            header = '\n'.join('[%s] %s' % m for m in meta)
            ticket_body = '%s\n\n%s\n\n---\n%s' % (
                header,
                form.cleaned_data['problem_description'],
                requestor_meta
            )

            ticket = rtModels.Ticket(subject=form.cleaned_data['subject'],
                                     problem_description="\n  ".join(ticket_body.splitlines()),
                                     requestor=form.cleaned_data['email'],
                                     cc=form.cleaned_data.get('cc', ''))

            logger.debug('Creating ticket for user: %s' % form.cleaned_data)

            rt = rtUtil.DjangoRt()
            ticket_id = rt.createTicket(ticket)
            if ticket_id > -1:
                messages.success(request, 'Your ticket has been submitted.')
                if 'attachment' in request.FILES:
                    rt.replyToTicket(
                        ticket_id,
                        files=([request.FILES['attachment'].name,
                                request.FILES['attachment'],
                                mimetypes.guess_type(request.FILES['attachment'].name)],
                               ))

                if request.user.is_authenticated:
                    return HttpResponseRedirect(reverse('djangoRT:ticketdetail',
                                                        args=[ticket_id]))
                else:
                    return HttpResponseRedirect(reverse('djangoRT:ticketcreate'))
            else:
                messages.error(
                    request, 'There was an error creating your ticket. Please try again.')
        else:
            messages.error(request, 'You ticket is missing some information. '
                                    'Please see below for details.')
    else:
        initial_data = {
            'subject': request.GET.get('subject'),
            'category': request.GET.get('category'),
            'problem_description': request.GET.get('problem_description'),
            'error_page': request.GET.get('error_page'),
            'http_referer': request.GET.get('http_referer'),
        }
        if request.user.is_authenticated:
            initial_data['email'] = request.user.email
            initial_data['first_name'] = request.user.first_name
            initial_data['last_name'] = request.user.last_name
        form = form_cls(initial=initial_data)
    return render(request, template_name, {'form': form})

@login_required
def ticketreply(request, ticketId):
    rt = rtUtil.DjangoRt()

    if not rt.hasAccess(ticketId, request.user.email):
        raise PermissionDenied

    ticket = rt.getTicket(ticketId)
    if request.method == 'POST':
        form = forms.ReplyForm(request.POST, request.FILES)

        if form.is_valid():
            reply_text = '[Reply from] {}\n\n{}\n\n---\n{} {} <{}>'.format(
                request.user.username,
                form.cleaned_data['reply'],
                request.user.first_name,
                request.user.last_name,
                request.user.email
            )
            attachments = []
            if 'attachment' in request.FILES:
                attachments.append(
                    (
                       request.FILES['attachment'].name,
                       request.FILES['attachment'],
                       mimetypes.guess_type(request.FILES['attachment'].name),
                    ))
            if rt.replyToTicket(ticketId, text=reply_text, files=attachments):
                return HttpResponseRedirect(reverse('djangoRT:ticketdetail',
                                                    args=[ticketId]))
    else:
        form = forms.ReplyForm()

    return render(request, 'djangoRT/ticketReply.html', {
        'ticket_id': ticketId,
        'ticket': ticket,
        'form': form
    })

@login_required
def ticketclose(request, ticketId):
    rt = rtUtil.DjangoRt()

    if not rt.hasAccess(ticketId, request.user.email):
        raise PermissionDenied

    ticket = rt.getTicket(ticketId)
    data = {}

    if request.method == 'POST':
        form = forms.CloseForm(request.POST)
        if form.is_valid():
            if (rt.commentOnTicket(ticketId, text=form.cleaned_data['reply']) and
                    rt.closeTicket(ticketId)):
                return HttpResponseRedirect(reverse('djangoRT:ticketdetail',
                                                    args=[ticketId]))
    else:
        form = forms.CloseForm(initial=data)
    return render(request, 'djangoRT/ticketClose.html', {
        'ticket_id': ticketId,
        'ticket': ticket,
        'form': form
    })


@login_required
def ticketattachment(request, ticketId, attachmentId):
    title, attachment = rtUtil.DjangoRt().getAttachment(ticketId, attachmentId)
    if attachment['Headers']['Content-Disposition'] == 'inline':
        return render(request, 'djangoRT/attachment.html', {'attachment' : attachment['Content'], 'ticketId' : ticketId, 'title' : title});
    else:
        response = HttpResponse(attachment['Content'], content_type=attachment['Headers']['Content-Type'])
        response['Content-Disposition'] = attachment['Headers']['Content-Disposition']
        return response

designsafe/apps/djangoRT/templates/djangoRT/access_denied.html
{% extends "base.html" %}
{% block title %}Access Denied{% endblock %}
{% block content %}
<div class="container">
    <h2>You do not have the correct permissions to access this page.</h2>
</div>
{% endblock %}

designsafe/apps/djangoRT/templates/djangoRT/attachment.html
{% extends "base.html" %}

{% block title %}Ticket #{{ ticket_id }}{% endblock %}

{% block content %}
<div class="container">
    <h2>Attachment : {{ title }} </h2>
    <pre>{{ attachment }}</pre>
    <a href="{% url 'djangoRT:ticketdetail' ticketId %}"><i class="fa fa-reply"></i> Back to ticket</a>
</div>
{% endblock %}

designsafe/apps/djangoRT/templates/djangoRT/navigation.html
<a class="btn btn-default btn-sm" href="{% url 'djangoRT:mytickets' %}">
  <i class="fa fa-long-arrow-left"></i> Back to ticket listing
</a>

{% if ticket_id %}
  <a class="btn btn-default btn-sm" href="{% url 'djangoRT:ticketdetail' ticket_id %}">
    <i class="fa fa-long-arrow-left"></i> Back to ticket
  </a>
{% endif %}

designsafe/apps/djangoRT/templates/djangoRT/reply.html
<a class="btn btn-default btn-sm" href="{% url 'djangoRT:ticketreply' ticket.id %}">
  <i class="fa fa-reply"></i>
  {% if ticket.Status == 'resolved' or ticket.Status == 'closed' %}
    Reopen this ticket
  {% else %}
    Reply to this ticket
  {% endif %}
</a>
{% if ticket.Status != 'resolved' and ticket.Status != 'closed' %}
<a class="btn btn-default btn-sm" href="{% url 'djangoRT:ticketclose' ticket.id %}">
  <i class="fa fa-times"></i>
    Close this ticket
</a>
 {% endif %}
<a class="btn btn-default btn-sm" href="{% url 'djangoRT:mytickets' %}">
  <i class="fa fa-home"></i>
  Return to ticket listing
</a>

designsafe/apps/djangoRT/templates/djangoRT/ticket.html
{% load i18n %}
<td>
  <span class="label {% if ticket.Status == 'resolved' or ticket.Status == 'closed' %}label-default{% else %}label-info{% endif %}">
    {% trans ticket.Status %}
  </span>
</td>
<td>
  <a href="{% url 'djangoRT:ticketdetail' ticket.id %}"> #{{ ticket.id }} : {{ ticket.Subject }}</a>
</td>
<td>
  {{ticket.LastUpdated|date:"M j Y P"}}
</td>
<td>
  <div class="btn-group">
    <a class="btn btn-info"
       title="{% if ticket.Status == 'resolved' or ticket.Status == 'closed' %}Reopen this ticket{% else %}Reply to this ticket{% endif %}"
       href="{% url 'djangoRT:ticketreply' ticket.id %}">
      <i class="fa fa-reply"></i>
      <span class="sr-only">
        {% if ticket.Status == 'resolved' or ticket.Status == 'closed' %}Reopen this ticket{% else %}Reply to this ticket{% endif %}
      </span>
    </a>
    {% if ticket.Status != 'resolved' and ticket.Status != 'closed' %}
      <a class="btn btn-danger"
         title="Close this ticket"
         href="{% url 'djangoRT:ticketclose' ticket.id %}">
        <i class="fa fa-times"></i>
        <span class="sr-only">Close this ticket</span>
      </a>
    {% endif %}
  </div>
</td>

designsafe/apps/djangoRT/templates/djangoRT/ticketClose.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Close #{{ ticket_id }}{% endblock %}

{% block breadcrumb %}
<div class="container">
    <ul class="breadcrumb">
        <li><a href="{% url 'djangoRT:index' %}">Help</a></li>
        <li><a href="{% url 'djangoRT:mytickets' %}">My Tickets</a></li>
        <li><a href="{% url 'djangoRT:ticketdetail' ticket_id %}">{{ticket_id}}</a></li>
        <li class="active">Close Ticket</li>
    </ul>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <h2>
      Close #{{ ticket_id }} : {{ ticket.Subject }}
    </h2>

    <div class='reply_description'>
      Are you sure you want to close this ticket? Please provide a comment.
    </div>

    <form method="POST" enctype="multipart/form-data" action="">
      {% csrf_token %}

      {% bootstrap_form form %}

        <button class="btn btn-success" type="submit">
          Close
        </button>
        <a href="{% url 'djangoRT:ticketdetail' ticket_id %}" class="btn btn-default">Cancel</a>
    </form>
</div>
{% endblock %}

designsafe/apps/djangoRT/templates/djangoRT/ticketCreate.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Create a Ticket{% endblock %}

{% block breadcrumb %}
<div class="container">
    <ul class="breadcrumb">
        <li><a href="{% url 'djangoRT:index' %}">Help</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'djangoRT:mytickets' %}">My Tickets</a></li>
        {% endif %}
        <li class="active">Create Ticket</li>
    </ul>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Submit a new ticket</h1>
    <p>
        If your question isn't answered by our <a href="{% url 'pages-details-by-slug' slug='faq' %}">FAQ</a> 
        or <a href="{% url 'pages-details-by-slug' slug='rw/user-guides' %}">User Guides</a>,
        please use this form to contact us with your questions.
    </p>
    <p><i>Fields marked with <label class="required"></label> are required.</i></p>
    <p>Please include where applicable:</p>
    <ul>
      <li>Which app/version of app is involved?</li>
      <li>Which files are involved?</li>
      <li>What is the error message displayed?</li>
      <li>Please include any applicable screen shots.</li>
      <li>If this is a typo or page request update, please include the DesignSafe web address of the page in question.</li>
      <li>Please include as much information as possible about your issue so that it can be addressed as soon as possible.</li>
      <li>If it is an access permission issue please include the following:</li>
        <ul>
          <li>The name of project.</li>
          <li>The directory or file.</li>
          <li>the owner or PI of the project.</li>
        </ul>
    </ul>
    <form method="POST" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {% bootstrap_form form %}

        <button type="submit" class="btn btn-success">Create Ticket</button>
        {% if user.is_authenticated %}
        <a href="{% url 'djangoRT:mytickets' %}" class="btn btn-default">Cancel</a>
        {% endif %}
    </form>
</div>
{% endblock %}

designsafe/apps/djangoRT/templates/djangoRT/ticketDetail.html
{% extends "base.html" %}
{% load staticfiles sekizai_tags tz %}
{% block title %}Ticket #{{ ticket_id }}{% endblock %}

{% block breadcrumb %}
<div class="container">
    <ul class="breadcrumb">
        <li><a href="{% url 'djangoRT:index' %}">Help</a></li>
        <li><a href="{% url 'djangoRT:mytickets' %}">My Tickets</a></li>
        <li class="active">{{ticket_id}}</li>
    </ul>
</div>
{% endblock %}

{% block content %}

<div class="container">
    <h1>{{ ticket.Subject }}<br><small>Ticket #{{ ticket_id }}</small></h1>

    <div>
        <b>Actions:</b>
        <a class="btn btn-info" href="{% url 'djangoRT:ticketreply' ticket.id %}">
            <i class="fa fa-reply"></i>
            {% if ticket.Status == 'resolved' or ticket.Status == 'closed' %}Reopen this ticket{% else %}Reply to this ticket{% endif %}
        </a>
        {% if ticket.Status != 'resolved' and ticket.Status != 'closed' %}
        <a class="btn btn-danger" href="{% url 'djangoRT:ticketclose' ticket.id %}">
            <i class="fa fa-times"></i> Close this ticket
        </a>
        {% endif %}
    </div>

    <div class="row">
        <div class="col-md-9">
            {% for history in ticket_history %}
            {% if history.Type == "Correspond" or history.Type == "Create" %}
            <div class="history-item history-item-{{history.Type|lower}}">
                <h4>
                    <i class="fa fa-{% if history.Type == "Correspond" %}comment{% elif history.Type == 'Create' %}plus-circle{% endif %}"></i>
                    {% localtime off %}
                        {{history.Created|date:"M j Y P"}}
                    {% endlocaltime %}
                    <small>{{history.Description}}</small>
                </h4>

                <pre>{{history.Content}}</pre>

                {% if history.Attachments %}
                    <h5>Attachments:</h5>
                    {% for attachment_id, title in history.Attachments %}
                        <a href="{% url 'djangoRT:ticketattachment' ticket_id attachment_id %}">{{ title }}</a> <br />
                    {% endfor %}
                {% endif %}
            </div>
            {% elif history.Type == "Status" %}
            <div class="history-item history-item-{{history.Type|lower}}">
                <blockquote>
                    <i class="fa fa-bell"></i>
                    {{history.Description }}<br>
                    {% localtime off %}
                        {{history.Created|date:"M j Y P"}}
                    {% endlocaltime %}
                </blockquote>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>

    <div>
        <b>Actions:</b>
        <a class="btn btn-info" href="{% url 'djangoRT:ticketreply' ticket.id %}">
            <i class="fa fa-reply"></i>
            {% if ticket.Status == 'resolved' or ticket.Status == 'closed' %}Reopen this ticket{% else %}Reply to this ticket{% endif %}
        </a>
        {% if ticket.Status != 'resolved' and ticket.Status != 'closed' %}
        <a class="btn btn-danger" href="{% url 'djangoRT:ticketclose' ticket.id %}">
            <i class="fa fa-times"></i> Close this ticket
        </a>
        {% endif %}
    </div>
</div>
{% endblock %}

designsafe/apps/djangoRT/templates/djangoRT/ticketList.html
{% extends "base.html" %}
{% load staticfiles sekizai_tags tz %}
{% block title %}My Tickets{% endblock %}

{% block breadcrumb %}
<div class="container">
    <ul class="breadcrumb">
        <li><a href="{% url 'djangoRT:index' %}">Help</a></li>
        <li class="active">My Tickets</li>
    </ul>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <h1>My Tickets</h1>

  <a class="btn btn-primary" href="{% url 'djangoRT:ticketcreate' %}">
    <i class="fa fa-plus-circle"></i>
    Create a new ticket
  </a>

  {% if show_resolved %}
    <h3>
      All Tickets
      <small>
        <a class="btn btn-default btn-xs pull-right" href="{% url 'djangoRT:mytickets' %}">
          Show only open tickets
        </a>
      </small>
    </h3>
  {% else %}
    <h3>
      Open Tickets
      <small>
        <a class="btn btn-default btn-xs pull-right" href="{% url 'djangoRT:mytickets' %}?show_resolved">
          Show resolved tickets
        </a>
      </small>
    </h3>
  {% endif %}

  <form action="">
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-filter"></i></span>
        <input class="form-control search" type="text" id="search" placeholder="Filter tickets">
      </div>
    </div>
  </form>

  <div class="table-responsive">
    <table class="tickets table table-striped">
      <thead>
      <th>Status</th>
      <th>Ticket ID / Subject</th>
      <th>Last Updated</th>
      <th>Actions</th>
      </thead>
      <tbody>
        {% for ticket in tickets %}
          <tr class="ticket">
            {% include "djangoRT/ticket.html" %}
          </tr>
        {% empty %}
          <tr>
            <td colspan="4">
              <div class="jumbotron">
                <p>No tickets to display!</p>
              </div>
            </td>
          </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% addtoblock "js" %}
<script src="{% static 'djangoRT/js/djangoRT.js' %}"></script>
{% endaddtoblock %}
{% endblock %}