designsafe/apps/accounts/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from designsafe.apps.accounts import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/$', views.manage_profile, name='manage_profile'),
    url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
    url(r'^professional-profile/$', views.manage_pro_profile, name='manage_pro_profile'),
    url(r'^professional-profile/edit$', views.pro_profile_edit, name='pro_profile_edit'),
    url(r'^authentication/$', views.manage_authentication, name='manage_authentication'),
    url(r'^identities/$', views.manage_identities, name='manage_identities'),
    url(r'^licenses/$', views.manage_licenses, name='manage_licenses'),
    url(r'^applications/$', views.manage_applications, name='manage_applications'),
    url(r'^notifications/settings/$', views.manage_notifications, name='manage_notifications'),
    url(r'^register/$', views.register, name='register'),
    url(r'^nees-account/(?:(?P<step>\d+)/)?$', views.nees_migration, name='nees_migration'),
    url(r'^registration-successful/$', views.registration_successful, name='registration_successful'),
    url(r'^password-reset/(?:(?P<code>.+)/)?$', views.password_reset, name='password_reset'),
    url(r'^activate/(?:(?P<code>.+)/)?$', views.email_confirmation, name='email_confirmation'),
    url(r'^departments\.json$', views.departments_json, name='departments_json'),

    url(r'^mailing-list/(?P<list_name>.*)/$', views.mailing_list_subscription,
        name='mailing_list_subscription'),

    url(r'^user-report/(?P<list_name>.*)/$', views.user_report,
        name='user_report'),

    url(r'^terms-conditions/$', views.termsandconditions, name="terms_conditions"),
]


def menu_items(**kwargs):
    if 'type' in kwargs and kwargs['type'] == 'account':
        return [
            {
                'label': _('Account Profile'),
                'url': reverse('designsafe_accounts:index'),
                'children': [],
            },
        ]

designsafe/apps/api/notifications/urls.py
from django.conf.urls import include, url

from designsafe.apps.api.notifications.views.api import ManageNotificationsView, NotificationsBadgeView
from designsafe.apps.api.notifications.views.webhooks import JobsWebhookView, FilesWebhookView

urlpatterns = [
    url(r'^$', ManageNotificationsView.as_view(), name='index'),
    url(r'^badge/$', NotificationsBadgeView.as_view(), name='badge'),
    url(r'^notifications/(?P<event_type>\w+)/?$', ManageNotificationsView.as_view(), name='event_type_notifications'),
    url(r'^delete/(?P<pk>\w+)?$', ManageNotificationsView.as_view(),
                                        name='delete_notification'),
    url(r'^wh/jobs/$', JobsWebhookView.as_view(), name='jobs_wh_handler'),
    url(r'^wh/files/$', FilesWebhookView.as_view(), name='files_wh_handler'),
]

designsafe/apps/auth/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from designsafe.apps.auth import views

urlpatterns = [
    url(r'^$', views.login_options, name='login'),
    url(r'^logged-out/$', views.logged_out, name='logout'),
    url(r'^agave/$', views.agave_oauth, name='agave_oauth'),
    url(r'^agave/callback/$', views.agave_oauth_callback, name='agave_oauth_callback'),
    url(r'^agave/session-error/$', views.agave_session_error, name='agave_session_error'),
]


def menu_items(**kwargs):
    if 'type' in kwargs and kwargs['type'] == 'account':
        return [
            {
                'label': _('Login'),
                'url': reverse('login'),
                'children': [],
                'visible': False
            },
            {
                'label': _('Login'),
                'url': reverse('designsafe_auth:login'),
                'children': [],
                'visible': False
            },
            {
                'label': _('Agave'),
                'url': reverse('designsafe_auth:agave_session_error'),
                'children': [],
                'visible': False
            }
        ]

designsafe/apps/djangoRT/urls.py
from django.conf.urls import url

from designsafe.apps.djangoRT import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new-ticket/$', views.ticketcreate, name='ticketcreate'),
    # url(r'^new-ticket/guest/$', views.ticketcreateguest, name='ticketcreateguest'),
    url(r'^tickets/$', views.mytickets, name='mytickets'),
    url(r'^tickets/(?P<ticketId>\d+)/$', views.ticketdetail, name='ticketdetail'),
    url(r'^tickets/(?P<ticketId>\d+)/reply/$', views.ticketreply, name='ticketreply'),
    url(r'^tickets/(?P<ticketId>\d+)/close/$', views.ticketclose, name='ticketclose'),
    url(r'^tickets/(?P<ticketId>\d+)/attachment/(?P<attachmentId>\d+)/$', views.ticketattachment, name='ticketattachment'),
]

designsafe/apps/notifications/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from designsafe.apps.notifications import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^notifications/$', views.notifications, name='notifications'),

    # url(r'^apps-list/$', 'apps_list', name='apps_list'),
    # url(r'^files-list/$', 'files_list', name='files_list'),
    # url(r'^jobs-list/$', 'jobs_list', name='jobs_list'),
    # url(r'^jobs-details/$', 'jobs_details', name='jobs_details'),
]


def menu_items(**kwargs):
    if 'type' in kwargs and kwargs['type'] == 'account':
        return [
            {
                'label': _('Notifications'),
                'url': reverse('designsafe_notifications:index'),
                'children': []
            }
        ]

designsafe/urls.py
"""
DesignSafe-CI URL Configuration
===============================

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/

Examples:
---------

**Function views**

#. Add an import:  from my_app import views
#. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')

**Class-based views**

#. Add an import:  from other_app.views import Home
#. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
    
**Including another URLconf**

#. Add an import:  from blog import urls as blog_urls
#. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from designsafe.apps.auth.views import login_options as des_login_options
from django.contrib.auth.views import logout as des_logout
from designsafe.views import project_version as des_version

# sitemap - classes must be imported and added to sitemap dictionary
from django.contrib.sitemaps.views import sitemap
from cms.sitemaps import CMSSitemap
from designsafe.sitemaps import StaticViewSitemap, DynamicViewSitemap, HomeSitemap, ProjectSitemap, SubSitemap
from designsafe import views

# cms preferences
CMSSitemap.priority = 0.7
CMSSitemap.changefreq = 'weekly'

sitemaps = {
    'home': HomeSitemap,
    'subsite': SubSitemap,
    'static': StaticViewSitemap,
    'dynamic': DynamicViewSitemap,
    'projects': ProjectSitemap,
    'cmspages': CMSSitemap,
}

urlpatterns = [
    # admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/impersonate/', include('impersonate.urls')),

    # sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # terms-and-conditions
    url(r'^terms/', include('termsandconditions.urls')),

    url(r'^api/', include('designsafe.apps.api.urls', namespace='designsafe_api')),

    # RAMP verification
    url(r'{}.html$'.format(settings.RAMP_VERIFICATION_ID), TemplateView.as_view(template_name='ramp_verification.html')),
    
    # api urls, just for the samples.
    url(r'^applications/', include('designsafe.apps.applications.urls',
                                namespace='designsafe_applications')),
    url(r'^data/', include('designsafe.apps.data.urls', namespace='designsafe_data')),
    url(r'^rw/workspace/', include('designsafe.apps.workspace.urls',
                                   namespace='designsafe_workspace')),
    url(r'^notifications/', include('designsafe.apps.notifications.urls',
                                    namespace='designsafe_notifications')),
    url(r'^search/', include('designsafe.apps.search.urls',
                                    namespace='designsafe_search')),
    url(r'^geo/', include('designsafe.apps.geo.urls',
                                    namespace='designsafe_geo')),
    url(r'^recon-portal/', include('designsafe.apps.rapid.urls',
                                    namespace='designsafe_rapid')),


    # auth
    url(r'^account/', include('designsafe.apps.accounts.urls',
        namespace='designsafe_accounts')),
    url(r'^register/$', RedirectView.as_view(
        pattern_name='designsafe_accounts:register', permanent=True), name='register'),

    # dashboard
    url(r'^dashboard/', include('designsafe.apps.dashboard.urls',
        namespace='designsafe_dashboard')),

    # need a fancier redirect here to pass the code param along
    url(r'^activate/(?:(?P<code>.+)/)?$',
        lambda x, code: HttpResponseRedirect(
            reverse('designsafe_accounts:email_confirmation',
                    args=[code] if code else None)
        )),
    url(r'^password-reset/(?:(?P<code>.+)/)?$',
        lambda x, code: HttpResponseRedirect(
            reverse('designsafe_accounts:password_reset',
                    args=[code] if code else None)
        )),

    # box
    url(r'^account/applications/box/', include('designsafe.apps.box_integration.urls',
        namespace='box_integration')),

    # dropbox
    url(r'^account/applications/dropbox/', include('designsafe.apps.dropbox_integration.urls',
        namespace='dropbox_integration')),

    # googledrive
    url(r'^account/applications/googledrive/', include('designsafe.apps.googledrive_integration.urls',
        namespace='googledrive_integration')),

    # google site verification
    url(r'{}.html$'.format(settings.GOOGLE_SITE_VERIFICATION_ID), TemplateView.as_view(template_name='google_verification.html')),

    # auth
    url(r'^auth/', include('designsafe.apps.auth.urls', namespace='designsafe_auth')),

    url(r'^login/$', des_login_options, name='login'),
    url(r'^logout/$', des_logout,
        {'next_page': '/auth/logged-out/'}, name='logout'),

    # help
    url(r'^help/', include('designsafe.apps.djangoRT.urls', namespace='djangoRT')),

    # webhooks
    url(r'^webhooks/', include('designsafe.webhooks')),

    # version check
    url(r'^version/', des_version),

    # cms handles everything else
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),

]
if settings.DEBUG: 
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

designsafe/apps/notifications/models.py
from django.db import models
from django.dispatch import receiver
from designsafe.apps.signals.signals import generic_event
from .apps import Event
import datetime
import json
import cgi


class Notification(models.Model):
    # what are the agave length defaults?
    event_type = models.CharField(max_length=50)
    user = models.CharField(max_length=20)
    read = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    notification_time = models.DateTimeField(default=datetime.datetime.now, blank=True)
    body = models.TextField()

    @property
    def content(self):
        return json.loads(self.body)

    def mark_read(self):
        self.read = True
        self.save()

    def mark_deleted(self):
        self.deleted = True
        self.save()


@receiver(generic_event)
def receive_notification(sender, **kwargs):
    event_type = kwargs.get('event_type')
    event_data = kwargs.get('event_data')
    event_users = kwargs.get('event_users')

    d = []
    if 'html' in event_data:
        for item in event_data['html']:
            for key, value in item.items():
                if key != 'action_link':
                    key= cgi.escape(key)
                    value= cgi.escape(value)
                    d.append({key:value})

    event_data['html'] = d

    for user in event_users:
        notification = Notification(event_type=event_type, user=user,
                                    body=json.dumps(event_data))
        notification.save()

    Event.send_event(event_type, event_users, event_data)

designsafe/apps/api/notifications/views/api.py
import logging
import requests
from django.http.response import HttpResponseBadRequest
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render

from designsafe.apps.api.notifications.models import Notification

from designsafe.apps.api.views import BaseApiView
from designsafe.apps.api.mixins import JSONResponseMixin, SecureMixin
from designsafe.apps.api.exceptions import ApiException

import json

logger = logging.getLogger(__name__)


class ManageNotificationsView(SecureMixin, JSONResponseMixin, BaseApiView):

    def get(self, request, event_type = None, *args, **kwargs):
        limit = request.GET.get('limit', 0)
        page = request.GET.get('page', 0)
        if event_type is not None:
            notifs = Notification.objects.filter(event_type = event_type,
                          deleted = False,
                          user = request.user.username).order_by('-datetime')
            total = Notification.objects.filter(event_type = event_type,
                          deleted = False,
                          user = request.user.username).count()
        else:
            notifs = Notification.objects.filter(deleted = False,
                          user = request.user.username).order_by('-datetime')
            total = Notification.objects.filter(deleted = False,
                          user = request.user.username).count()
        if limit:
            limit = int(limit)
            page = int(page)
            offset = page * limit
            notifs = notifs[offset:offset+limit]

        for n in notifs:
            if not n.read:
                n.mark_read()

        notifs = [n.to_dict() for n in notifs]
        return self.render_to_json_response({'notifs':notifs, 'page':page, 'total': total})

    def post(self, request, *args, **kwargs):
        body_json = json.loads(request.body)
        nid = body_json['id']
        read = body_json['read']
        n = Notification.objects.get(pk = nid) #?
        n.read = read
        n.save()
        return self.render_to_json_response(n)

    def delete(self, request, pk, *args, **kwargs):
        if pk == 'all':
            items=Notification.objects.filter(deleted=False, user=str(request.user))
            for i in items:
                i.mark_deleted()
        else:
            x = Notification.objects.get(pk=pk)
            x.mark_deleted()

        return HttpResponse('OK')

class NotificationsBadgeView(SecureMixin, JSONResponseMixin, BaseApiView):

    def get(self, request, *args, **kwargs):
        unread = Notification.objects.filter(deleted = False, read = False,
                      user = request.user.username).count()
        return self.render_to_json_response({'unread': unread})

designsafe/apps/api/notifications/views/webhooks.py
from django.http.response import HttpResponseBadRequest
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.sessions.models import Session
from django.conf import settings

from celery import shared_task
from requests import ConnectionError, HTTPError
from agavepy.agave import Agave, AgaveException

from designsafe.apps.api.notifications.models import Notification

from designsafe.apps.api.views import BaseApiView
from designsafe.apps.api.mixins import JSONResponseMixin, SecureMixin
from designsafe.apps.api.exceptions import ApiException

from designsafe.apps.workspace.tasks import handle_webhook_request

import json
import logging

logger = logging.getLogger(__name__)



class JobsWebhookView(JSONResponseMixin, BaseApiView):
    """
    Dispatches notifications when receiving a POST request from the Agave
    webhook service.

    """

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(JobsWebhookView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return HttpResponse(settings.WEBHOOK_POST_URL.strip('/') + '/api/notifications/wh/jobs/')

    def post(self, request, *args, **kwargs):
        """
        Calls handle_webhook_request on webhook JSON body
        to notify the user of the progress of the job.

        """

        job = json.loads(request.body)

        handle_webhook_request(job)
        return HttpResponse('OK')


class FilesWebhookView(SecureMixin, JSONResponseMixin, BaseApiView):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(FilesWebhookView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        notification = json.loads(request.body)
        logger.debug(notification)

        return HttpResponse('OK')

designsafe/apps/accounts/templates/designsafe/apps/accounts/base.html
{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="headline headline-research">{{title}}</h1>
    <div class="row">
      <div class="col-sm-3">
        <ul class="nav nav-pills nav-stacked">
          {% url 'designsafe_accounts:manage_profile' as item_url %}
          <li {% if item_url in request.path %}class="active"{% endif %}><a href="{{item_url}}">Account Profile</a></li>

          {% url 'designsafe_accounts:manage_pro_profile' as item_url %}
          <li {% if item_url in request.path %}class="active"{% endif %}><a href="{{item_url}}">Professional Profile</a></li>

          {% url 'designsafe_accounts:manage_authentication' as item_url %}
          <li {% if request.path == item_url %}class="active"{% endif %}><a href="{{item_url}}">Authentication</a></li>

          <!--
          {% url 'designsafe_accounts:manage_identities' as item_url %}
          <li {% if request.path == item_url %}class="active"{% endif %}><a href="{{item_url}}">Identities</a></li>
          -->

          {% url 'designsafe_accounts:manage_licenses' as item_url %}
          <li {% if request.path == item_url %}class="active"{% endif %}><a href="{{item_url}}">Software Licenses</a></li>

          {% url 'designsafe_accounts:manage_notifications' as item_url %}
          <li {% if request.path == item_url %}class="active"{% endif %}><a href="{{item_url}}">Notification Settings</a></li>

          {% url 'designsafe_accounts:manage_applications' as item_url %}
          <li {% if request.path == item_url %}class="active"{% endif %}><a href="{{item_url}}">3rd Party Applications</a></li>

          <!-- {% url 'tc_view_page' as item_url %} -->
          {% url 'designsafe_accounts:terms_conditions' as item_url %}
          <li {% if request.path == item_url %}class="active"{% endif %}><a href="{{item_url}}">Terms and Conditions</a></li>
        </ul>
        <br>
      </div>
      <div class="col-sm-9">
        {% block panel_content %}{% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

designsafe/apps/accounts/templates/designsafe/apps/accounts/manage_licenses.html
{% extends "designsafe/apps/accounts/base.html" %}

{% block panel_content %}
<div class="panel panel-default">
    <div class="panel-body">
        <h2>Software Licenses</h2>

        <p class="lead">
            DesignSafe makes available to users a number of software programs, some of which are
            commercial and require licenses to use. Below you can review and find details
            on how to obtain and/or activate your license to use licensed software.
        </p>

        {% for license in licenses %}
            <hr>
            <div class="license {% if license.current_user_license %}license-active{% endif %}">
                <h3>
                    {{license.license_type}}
                    {% if license.current_user_license %}
                        <span class="label label-success"><i class="fa fa-check-circle"></i> ACTIVE </span>
                    {% else %}
                        <span class="label label-danger"> NOT ACTIVE </span>
                    {% endif %}
                </h3>
                {% include license.details_html %}
                {% if not license.current_user_license %}
                    <p>
                        <a class="btn btn-lg btn-default"
                           href="{% url 'djangoRT:ticketcreate' %}?category=OTHER&subject={{license.license_type}}+license+activation+request{% if license.license_type == 'LS-DYNA' %}&problem_description=Department+Name%3A%0DInstitution+Name%3A{% endif %}"
                           target="_blank"
                        >
                            Request Activation
                        </a>
                    </p>
                {% else %}
                    <p class="text-success">{{license.license_type}} is activated for your account.</p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

designsafe/apps/accounts/templates/designsafe/apps/accounts/nees_migration.html
{% extends "base.html" %}

{% load bootstrap3 sekizai_tags staticfiles %}

{% block title %}Accessing DesignSafe{% endblock %}

{% block content %}
<div class="container">
    <h1 class="headline headline-research">Accessing DesignSafe</h1>

    <p class="lead">
        <a href="https://nees.org/">NEES</a> users can easily gain access to DesignSafe
        using their NEEShub account email address. We will then guide you through the
        steps required to create an account. Welcome to DesignSafe!
    </p>

    <p class="lead">
        To begin, please enter the email address associated with your NEEShub account.
    </p>

    <form method="post" action="{% url 'designsafe_accounts:nees_migration' '1' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">Access DesignSafe Now</button>
        <a class="btn btn-link" href="/">Cancel</a>
        <a class="btn btn-link" href="{% url 'login' %}">Already have an account? Log in.</a>
    </form>

</div>
{% endblock %}

designsafe/apps/accounts/templates/designsafe/apps/accounts/nees_migration_block.html
{% load staticfiles %}
<div class="callout callout-default">
    <p class="lead">NEES Users: Accessing DesignSafe</p>
    <div style="display:flex;">
        <div style="padding-right:0.5em">
            <img alt="NEES.org" title="NEES.org logo"
                 src="{% static 'designsafe/apps/accounts/images/nees.png' %}">
        </div>
        <div style="flex-grow:2">
            <p>
                <a href="https://nees.org/">NEES</a> users can easily gain access to
                DesignSafe using their NEEShub account email address. We will then guide
                you through the steps required to create an account.
                Welcome to DesignSafe!
            </p>
        </div>
    </div>
    <a href="{% url 'designsafe_accounts:nees_migration' %}"
       class="btn btn-default btn-block">Access DesignSafe Now</a>
</div>

designsafe/apps/accounts/templates/designsafe/apps/accounts/nees_migration_step_1.html
{% extends "base.html" %}

{% load bootstrap3 sekizai_tags staticfiles %}

{% block title %}Create Account{% endblock %}

{% block content %}
<div class="container">
    <h1 class="headline headline-research">Create Account</h1>

    <p class="lead">
        We found the following NEEShub user matching the email address
        <b>{{email_address}}</b>:
    </p>

    <table class="table">
        <tbody>
        <tr>
            <td><b>Name</b></td>
            <td>
                {{nees_user_match.0.givenName}}
                {{nees_user_match.0.middleName}}
                {{nees_user_match.0.surname}}
            </td>
            <td></td>
        </tr>
        <tr>
            <td><b>Email</b></td>
            <td>{{nees_user_match.0.email}}</td>
            <td>
                {% if tas_by_email %}
                <div class="alert alert-warning">
                    <h4>A TACC User Account already exists with this email address!</h4>
                    <p>
                        If you already have an account you
                        <a href="{% url 'login' %}">can log in now.</a>
                    </p>
                </div>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td><b>NEEShub Username</b></td>
            <td>{{nees_user_match.0.username}}</td>
            <td>
                {% if tas_by_username %}
                <div class="alert alert-warning">
                    <h4>A TACC User Account already exists with this username!</h4>
                    <p>
                        If you already have an account you <a href="{% url 'login' %}">can
                        log in now.</a> If you are sure you do not already have a TACC
                        account, then you will need to choose a different username in the
                        next step.
                    </p>
                </div>
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>

    <form method="post"  action="{% url 'designsafe_accounts:nees_migration' '2' %}">
        {% csrf_token %}
        <input name="email_address" value="{{email_address}}" type="hidden">
        <button class="btn btn-primary" type="submit">Create Account</button>
        <a class="btn btn-link" href="{% url 'designsafe_accounts:nees_migration' %}">Cancel</a>
    </form>

</div>
{% endblock %}

designsafe/apps/accounts/templates/designsafe/apps/accounts/nees_migration_step_2.html
{% extends "base.html" %}

{% load bootstrap3 sekizai_tags staticfiles %}

{% block title %}Create Account{% endblock %}

{% block content %}
<div class="container">
    <h1 class="headline headline-research">Create Account</h1>

    <p class="lead">
        We have pre-filled as many fields as possible from the NEES User Profile you
        selected.<br>Please complete any missing data and submit.
    </p>

    <form method="post" action="{% url 'designsafe_accounts:nees_migration' '3' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">Create Account</button>
        <a class="btn btn-link" href="{% url 'designsafe_accounts:nees_migration' %}">Cancel</a>
    </form>
</div>
{% addtoblock 'js' %}
<script type="text/javascript" src="{% static 'designsafe/apps/accounts/js/institution_departments.js' %}"></script>
<script type="text/javascript" src="{% static 'designsafe/apps/accounts/js/new_institution.js' %}"></script>
{% endaddtoblock %}
{% endblock %}

designsafe/apps/accounts/templates/designsafe/apps/accounts/notifications.html
{% extends "base.html" %}
{% load sekizai_tags %}
{% load static %}
{% block title %}Notifications{% endblock %}

{% block content %}
<div class="container">
<h1 class="headline headline-research">Notifications</h1>
  <div ng-controller="NotificationListCtrl" ng-include="'{% static 'scripts/notifications/html/notification_list.html' %}'">
  {{message}}
<!--   {% if notifications %}
    <div class="alert alert-info">
      <h4>Coming soon!</h4>
      <p>
        Notifications will have action links to be able to jump to relevant pages to
        act on the notification.
      </p>
    </div>

    <ul class="list-group" ng-controller="NotificationListCtrl">
      {% for x in notifications %}
        <li class="list-group-item {% if x.read %} text-muted {% else %} text-info {% endif %}">
        <form id="delete_{{x.id}}" method="post" action ="{% url 'designsafe_accounts:delete_notification' %}">
          {% csrf_token %}
          <input name="id" type="hidden" value="{{x.id}}">
          <button name="delete" value="delete" type="submit">Delete</button>
        </form>
          <dl class="dl-horizontal">
            <dt>Type</dt>
            <dd>{{ x.event_type }}</dd>
            <dt>Time</dt>
            <dd>{{x.notification_time|date:'Y-m-d H:i'}}</dd>

            {% if x.event_type == 'job' %}
              <dt>Job name</dt>
              <dd>{{x.content.job_name}}</dd>

              <dt>Status</dt>
              <dd>{{x.content.status}}</dd>

              <dt>Archive path</dt>
              <dd>{{x.content.archive_path}}</dd>
            {% endif %}

            <dt>Raw message</dt>
            <dd>
              <p><button type="button" name="toggle-raw-message" class="btn btn-xs btn-default">Click to view</button></p>
              <p class="hide">{{x.body}}</p>
            </dd>
          </dl>
        </li>
      {% endfor %}
    </ul>

  {% else %}
    <div class="jumbotron text-center">
      <i class="fa fa-bell fa-2x text-muted"></i>
      <h2>No unread notifications.</h2>
      <p>
        You have no unread notifications.
        <a href="{% url 'designsafe_accounts:manage_notifications' %}">Click here</a>
        to manage your notification settings.
      </p>
    </div>
  {% endif %}
  </div> -->
</div>
{% addtoblock 'js' %}
<script>
  (function(window, $, undefined) {
    $('button[name="toggle-raw-message"]').on('click', function(e) {
      e.preventDefault();
      $(this).parent().next().toggleClass('show');
    });
  })(window, jQuery);
</script>
<script type="text/javascript" src="{% static 'designsafe/apps/notifications/scripts/app.js' %}"></script>
{% endaddtoblock %}

{% endblock %}