designsafe/apps/rapid/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
from designsafe.apps.rapid import views

urlpatterns = [
    url(r'^event-types/?$', views.get_event_types, name="get_event_types"),
    url(r'^events/?$', views.get_events, name="get_events"),
    url(r'^admin/?$', views.admin, name="admin"),
    url(r'^admin/users/?$', views.admin_users, name="admin_users"),
    url(r'^admin/users/permissions/?$', views.admin_user_permissions, name="admin_user_permissions"),
    url(r'^admin/create-event', views.admin_create_event, name="admin_create_event"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/delete$', views.admin_delete_event, name="admin_delete_event"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/$', views.admin_edit_event, name="admin_edit_event"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/datasets$', views.admin_event_datasets, name="admin_event_datasets"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/add-dataset/$', views.admin_event_add_dataset, name="admin_event_add_dataset"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/(?P<dataset_id>[-\w]+)/$', views.admin_event_edit_dataset, name="admin_event_edit_dataset"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/(?P<dataset_id>[-\w]+)/delete$', views.admin_event_delete_dataset, name="admin_event_delete_dataset"),
    url(r'^.*$', views.index, name='index'),

]

designsafe/urls.py
"""
DesignSafe-CI URL Configuration
===============================

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/

Examples:
---------

**Function views**

#. Add an import:  from my_app import views
#. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')

**Class-based views**

#. Add an import:  from other_app.views import Home
#. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
    
**Including another URLconf**

#. Add an import:  from blog import urls as blog_urls
#. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from designsafe.apps.auth.views import login_options as des_login_options
from django.contrib.auth.views import logout as des_logout
from designsafe.views import project_version as des_version

# sitemap - classes must be imported and added to sitemap dictionary
from django.contrib.sitemaps.views import sitemap
from cms.sitemaps import CMSSitemap
from designsafe.sitemaps import StaticViewSitemap, DynamicViewSitemap, HomeSitemap, ProjectSitemap, SubSitemap
from designsafe import views

# cms preferences
CMSSitemap.priority = 0.7
CMSSitemap.changefreq = 'weekly'

sitemaps = {
    'home': HomeSitemap,
    'subsite': SubSitemap,
    'static': StaticViewSitemap,
    'dynamic': DynamicViewSitemap,
    'projects': ProjectSitemap,
    'cmspages': CMSSitemap,
}

urlpatterns = [
    # admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/impersonate/', include('impersonate.urls')),

    # sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # terms-and-conditions
    url(r'^terms/', include('termsandconditions.urls')),

    url(r'^api/', include('designsafe.apps.api.urls', namespace='designsafe_api')),

    # RAMP verification
    url(r'{}.html$'.format(settings.RAMP_VERIFICATION_ID), TemplateView.as_view(template_name='ramp_verification.html')),
    
    # api urls, just for the samples.
    url(r'^applications/', include('designsafe.apps.applications.urls',
                                namespace='designsafe_applications')),
    url(r'^data/', include('designsafe.apps.data.urls', namespace='designsafe_data')),
    url(r'^rw/workspace/', include('designsafe.apps.workspace.urls',
                                   namespace='designsafe_workspace')),
    url(r'^notifications/', include('designsafe.apps.notifications.urls',
                                    namespace='designsafe_notifications')),
    url(r'^search/', include('designsafe.apps.search.urls',
                                    namespace='designsafe_search')),
    url(r'^geo/', include('designsafe.apps.geo.urls',
                                    namespace='designsafe_geo')),
    url(r'^recon-portal/', include('designsafe.apps.rapid.urls',
                                    namespace='designsafe_rapid')),


    # auth
    url(r'^account/', include('designsafe.apps.accounts.urls',
        namespace='designsafe_accounts')),
    url(r'^register/$', RedirectView.as_view(
        pattern_name='designsafe_accounts:register', permanent=True), name='register'),

    # dashboard
    url(r'^dashboard/', include('designsafe.apps.dashboard.urls',
        namespace='designsafe_dashboard')),

    # need a fancier redirect here to pass the code param along
    url(r'^activate/(?:(?P<code>.+)/)?$',
        lambda x, code: HttpResponseRedirect(
            reverse('designsafe_accounts:email_confirmation',
                    args=[code] if code else None)
        )),
    url(r'^password-reset/(?:(?P<code>.+)/)?$',
        lambda x, code: HttpResponseRedirect(
            reverse('designsafe_accounts:password_reset',
                    args=[code] if code else None)
        )),

    # box
    url(r'^account/applications/box/', include('designsafe.apps.box_integration.urls',
        namespace='box_integration')),

    # dropbox
    url(r'^account/applications/dropbox/', include('designsafe.apps.dropbox_integration.urls',
        namespace='dropbox_integration')),

    # googledrive
    url(r'^account/applications/googledrive/', include('designsafe.apps.googledrive_integration.urls',
        namespace='googledrive_integration')),

    # google site verification
    url(r'{}.html$'.format(settings.GOOGLE_SITE_VERIFICATION_ID), TemplateView.as_view(template_name='google_verification.html')),

    # auth
    url(r'^auth/', include('designsafe.apps.auth.urls', namespace='designsafe_auth')),

    url(r'^login/$', des_login_options, name='login'),
    url(r'^logout/$', des_logout,
        {'next_page': '/auth/logged-out/'}, name='logout'),

    # help
    url(r'^help/', include('designsafe.apps.djangoRT.urls', namespace='djangoRT')),

    # webhooks
    url(r'^webhooks/', include('designsafe.webhooks')),

    # version check
    url(r'^version/', des_version),

    # cms handles everything else
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),

]
if settings.DEBUG: 
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

designsafe/apps/rapid/models.py
from django.conf import settings
from datetime import datetime
import logging
from elasticsearch_dsl import (DocType, String, Date, Nested,
                               Boolean, GeoPoint, MetaField, Text,
                               Keyword)
#from designsafe.connections import connections
logger = logging.getLogger(__name__)

class RapidNHEventType(DocType):
    class Meta:
        index = settings.ES_INDICES['rapid']['name']
        doc_type = settings.ES_INDICES['rapid']['documents'][0]['name']
        dynamic = MetaField('strict')

    display_name = String(fields={
        '_exact': Keyword()
    })
    name = String(fields={
        '_exact': Keyword()
    })


class RapidNHEvent(DocType):
    class Meta:
        index = settings.ES_INDICES['rapid']['name']
        doc_type = settings.ES_INDICES['rapid']['documents'][1]['name']
        dynamic = MetaField('strict')

    event_date = Date()
    created_date = Date()
    title = Text(analyzer='english')
    event_type = String(fields={
                '_exact': Keyword()
            })
    location_description = Text(
        analyzer='english',
        fields={
            '_exact': Keyword()
        })
    location = GeoPoint()
    main_image_url = String(fields={
        '_exact': Keyword()
    })
    main_image_uuid = String(fields={
        '_exact': Keyword()
    })
    datasets = Nested(
        properties={
            "id": String(fields={
                '_exact': Keyword()
            }),
            "title": String(fields={
                '_exact': Keyword()
            }),
            "doi": String(fields={
                '_exact': Keyword()
            }),
            "url": String(fields={
                '_exact': Keyword()
            }),
        })

    def save(self, **kwargs):
        # self.created_date = datetime.utcnow()
        return super(RapidNHEvent, self).save(**kwargs)

designsafe/apps/rapid/forms.py
from django import forms
from designsafe.apps.rapid.models import RapidNHEvent, RapidNHEventType
import logging


logger = logging.getLogger(__name__)



class RapidNHEventForm(forms.Form):

    event_date = forms.DateField(label="Date of hazard event", required=True)
    title = forms.CharField(label="Event Title")
    event_type = forms.ChoiceField(label="Hazard Event Type", required=True)
    location_description = forms.CharField(label="Brief location description", required=True)
    lat = forms.FloatField(label="Latitude", required=True)
    lon = forms.FloatField(label="Longitude", required=True)
    image = forms.FileField(label="Banner image for detail", required=False)

    # def clean(self):
    #     cleaned_data = self.cleaned_data
    #     self.location = {
    #         "lat": cleaned_data['lat'],
    #         "lon": cleaned_data['lon']
    #     }
    #     logger.info(self)


class RapidNHEventDatasetForm(forms.Form):
    url = forms.CharField(label="Link to Data Depot", required=True)
    title = forms.CharField(label="Brief description of dataset", required=True)
    doi = forms.CharField(label="DOI", required=False)

designsafe/apps/rapid/templates/designsafe/apps/rapid/admin.html
{% extends "designsafe/apps/rapid/rapid_base.html" %}
{% load ds_filters %}

{% block main %}

  <div class="container rapid-admin">
    <div class="row">
      <div class="col-md-12">
        <h1> Recon Admin </h1>
        <a class="btn btn-success" href="{% url 'designsafe_rapid:admin_create_event' %}" target="_self">
          <i class="fa fa-plus"> Create New Recon Event </i>
        </a>
        <a class="btn btn-default pull-right" href="{% url 'designsafe_rapid:admin_users' %}" target="_self"> Recon User Admin </a>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <table class="table table-hover">
          <tr>
            <th> Title </th>
            <th> Event Date </th>
            <th> Event Type </th>
            <th> Location </th>
            <th> Created </th>
            <th> </th>
            <th> </th>
            <th> </th>
          </tr>
          {% for event in rapid_events %}
            <tr>
              <td> {{event.title}} </td>
              <td> {{event.event_date}} </td>
              <td> {{event.event_type}} </td>
              <td> {{event.location_description}} </td>
              <td> {{event.created_date}} </td>
              <td>
                <a href="{% url 'designsafe_rapid:admin_edit_event' event|private:'_id' %}" class="btn btn-sm btn-info" target="_self">
                  <i class="fa fa-file"> </i> Edit
                </a>
              </td>
              <td>
                <a href="{% url 'designsafe_rapid:admin_event_datasets' event|private:'_id' %}" class="btn btn-sm btn-info" target="_self">
                  <i class="fa fa-database"> </i> Datasets
                </a>
              </td>
              <td>
                <form action="{% url 'designsafe_rapid:admin_delete_event' event|private:'_id'  %}" method="POST">
                  {% csrf_token %}
                  <button class="btn btn-sm btn-danger"> <i class="fa fa-trash"> </i> Delete Event </button>
              </td>

            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>

{% endblock main %}

designsafe/apps/rapid/templates/designsafe/apps/rapid/admin_create_event.html
{% extends "designsafe/apps/rapid/rapid_base.html" %}
{% load ds_filters %}
{% load bootstrap3 sekizai_tags staticfiles %}


{% block main %}

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li> <a href="{% url 'designsafe_rapid:admin'%}" target="_self"> Recon Home </a></li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2> Create a Recon Natural Hazard Event </h2>
        <form method="post" action="" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="form-group">
            <button type="submit" class="btn btn-success"> <i class="fa fa-file"></i> Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>


{% addtoblock 'js' %}

<script>
  $(document).ready(function () {
    $('#id_event_date').datepicker({format: 'yyyy-mm-dd'});
  })
</script>

{% endaddtoblock %}

{% endblock main %}

designsafe/apps/rapid/templates/designsafe/apps/rapid/admin_edit_event.html
{% extends "designsafe/apps/rapid/rapid_base.html" %}
{% load ds_filters %}
{% load bootstrap3 sekizai_tags staticfiles %}



{% block main %}

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li> <a href="{% url 'designsafe_rapid:admin'%}" target="_self"> Recon Admin Home </a></li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2> Edit Natural Hazard Event </h2>

        <form method="post" action="" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% if event.main_image_uuid %}
            <div class="form-group">
              <label> Current banner image </label>
              <img ng-src="/uploads/RAPID/images/{{event.main_image_uuid}}" class="img-responsive"></img>
            </div>
          {% endif %}
          <div class="form-group">
            <button type="submit" class="btn btn-success"> <i class="fa fa-file"></i> Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>


{% addtoblock 'js' %}

<script>
  $(document).ready(function () {
    $('#id_event_date').datepicker({format: 'yyyy-mm-dd'});
  })
</script>

{% endaddtoblock %}

{% endblock main %}

designsafe/apps/rapid/templates/designsafe/apps/rapid/admin_event_add_dataset.html
{% extends "designsafe/apps/rapid/rapid_base.html" %}
{% load ds_filters %}
{% load bootstrap3 sekizai_tags staticfiles %}

{% block main %}

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li> <a href="{% url 'designsafe_rapid:admin'%}" target="_self"> Admin Home </a></li>
          <li> <a href="{% url 'designsafe_rapid:admin_event_datasets' event|private:'_id' %}" target="_self"> {{event.title}} </a></li>
        </ol>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h2> Add dataset to event: {{event.title}}</h2>
        <form method="post" action="">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="form-group">
            <button type="submit" class="btn btn-success"> <i class="fa fa-file"></i> Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>


{% addtoblock 'js' %}

{% endaddtoblock %}

{% endblock main %}

designsafe/apps/rapid/templates/designsafe/apps/rapid/admin_event_datasets.html
{% extends "designsafe/apps/rapid/rapid_base.html" %}
{% load ds_filters %}

{% block main %}

  <div class="container rapid-admin">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li> <a href="{% url 'designsafe_rapid:admin'%}" target="_self"> Admin Home </a></li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2> Datasets for event: "{{event.title}}" </h2>
        <a class="btn btn-success" href="{% url 'designsafe_rapid:admin_event_add_dataset' event|private:'_id' %}" target="_self">
          <i class="fa fa-plus"> Create New Dataset </i>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <table class="table table-hover">
          <tr>
            <th> DOI </th>
            <th> URL </th>
            <th> Title </th>
            <th></th>
            <th></th>
          </tr>
          {% for dataset in event.datasets %}
            <tr>
              <td> {{dataset.doi}} </td>
              <td> {{dataset.url}} </td>
              <td> {{dataset.title}} </td>
              <td> <a class="btn btn-info btn-sm"
                      href="{% url 'designsafe_rapid:admin_event_edit_dataset' event|private:'_id' dataset.id %}"
                      target="_self">
                      Edit
                    </a>
              </td>
              <td>
                <form method="POST" action="{% url 'designsafe_rapid:admin_event_delete_dataset' event|private:'_id' dataset.id %}">
                  {% csrf_token %}
                  <button class="btn btn-danger btn-sm"> Delete </button>
                </form>
              </td>

            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>

{% endblock main %}

designsafe/apps/rapid/templates/designsafe/apps/rapid/admin_event_edit_dataset.html
{% extends "designsafe/apps/rapid/rapid_base.html" %}
{% load ds_filters %}
{% load bootstrap3 sekizai_tags staticfiles %}

{% block main %}

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li> <a href="{% url 'designsafe_rapid:admin'%}" target="_self"> Admin Home </a></li>
          <li> <a href="{% url 'designsafe_rapid:admin_edit_event' event|private:'_id' %}" target="_self"> {{ event.title }} </a></li>
          <li> <a href="{% url 'designsafe_rapid:admin_event_datasets' event|private:'_id' %}" target="_self">  Datasets </a></li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2> Modify dataset to Recon Hazard Event </h2>
        <form method="post" action="">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="form-group">
            <button type="submit" class="btn btn-success"> <i class="fa fa-file"></i> Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% addtoblock 'js' %}
<script>
  $(document).ready(function () {
    $('#id_event_date').datepicker();
  })
</script>
{% endaddtoblock %}

{% endblock main %}

designsafe/apps/rapid/templates/designsafe/apps/rapid/index.html
{% extends "designsafe/apps/rapid/rapid_base.html" %}
{% block head_extra %}
    <base href="{% url 'designsafe_rapid:index' %}">
{% endblock %}




{% block main %}
<div class="">
  <div id="rapid">
    <div>
      <div ui-view></div>
    </div>
  </div>
</div>


{% endblock main %}

designsafe/apps/rapid/templates/designsafe/apps/rapid/rapid_base.html
{% extends "base.html" %}
{% load sekizai_tags %}
{% load static %}
{% load ds_filters %}

{% block head_extra %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
{% endblock %}




{% block content %}

  {% block main %} {% endblock main %}

{% addtoblock "js" %}
  <script type="text/javascript" src="{% static 'build/rapid.bundle.js' %}"></script>
{% endaddtoblock %}

{% addtoblock "css" %}
    <link rel="stylesheet" href="{% static 'build/rapid.bundle.css' %}" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" />
{% endaddtoblock %}

{% endblock content %}