designsafe/apps/api/urls.py
# pylint: disable=missing-docstring
from django.conf.urls import url, include
from designsafe.apps.api.views import LoggerApi

urlpatterns = [
    url(r'^agave/', include('designsafe.apps.api.agave.urls')),
    url(r'^public/', include('designsafe.apps.api.public_data.urls')),
    url(r'^projects/', include('designsafe.apps.api.projects.urls',
                               namespace='ds_projects_api')),
    url(r'^external-resources/', include('designsafe.apps.api.external_resources.urls')),

    url(r'^logger/$', LoggerApi.as_view(), name='logger'),
    url(r'^notifications/', include('designsafe.apps.api.notifications.urls')),
    url(r'^users/', include('designsafe.apps.api.users.urls')),
    url(r'^search/', include('designsafe.apps.api.search.urls', namespace="ds_search_api")),

]

designsafe/apps/auth/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from designsafe.apps.auth import views

urlpatterns = [
    url(r'^$', views.login_options, name='login'),
    url(r'^logged-out/$', views.logged_out, name='logout'),
    url(r'^agave/$', views.agave_oauth, name='agave_oauth'),
    url(r'^agave/callback/$', views.agave_oauth_callback, name='agave_oauth_callback'),
    url(r'^agave/session-error/$', views.agave_session_error, name='agave_session_error'),
]


def menu_items(**kwargs):
    if 'type' in kwargs and kwargs['type'] == 'account':
        return [
            {
                'label': _('Login'),
                'url': reverse('login'),
                'children': [],
                'visible': False
            },
            {
                'label': _('Login'),
                'url': reverse('designsafe_auth:login'),
                'children': [],
                'visible': False
            },
            {
                'label': _('Agave'),
                'url': reverse('designsafe_auth:agave_session_error'),
                'children': [],
                'visible': False
            }
        ]

designsafe/apps/djangoRT/urls.py
from django.conf.urls import url

from designsafe.apps.djangoRT import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new-ticket/$', views.ticketcreate, name='ticketcreate'),
    # url(r'^new-ticket/guest/$', views.ticketcreateguest, name='ticketcreateguest'),
    url(r'^tickets/$', views.mytickets, name='mytickets'),
    url(r'^tickets/(?P<ticketId>\d+)/$', views.ticketdetail, name='ticketdetail'),
    url(r'^tickets/(?P<ticketId>\d+)/reply/$', views.ticketreply, name='ticketreply'),
    url(r'^tickets/(?P<ticketId>\d+)/close/$', views.ticketclose, name='ticketclose'),
    url(r'^tickets/(?P<ticketId>\d+)/attachment/(?P<attachmentId>\d+)/$', views.ticketattachment, name='ticketattachment'),
]

designsafe/apps/geo/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
from designsafe.apps.geo import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^test/$', views.test, name='test'),
    url(r'^.*$', views.index, name="index"),

]

designsafe/apps/rapid/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
from designsafe.apps.rapid import views

urlpatterns = [
    url(r'^event-types/?$', views.get_event_types, name="get_event_types"),
    url(r'^events/?$', views.get_events, name="get_events"),
    url(r'^admin/?$', views.admin, name="admin"),
    url(r'^admin/users/?$', views.admin_users, name="admin_users"),
    url(r'^admin/users/permissions/?$', views.admin_user_permissions, name="admin_user_permissions"),
    url(r'^admin/create-event', views.admin_create_event, name="admin_create_event"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/delete$', views.admin_delete_event, name="admin_delete_event"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/$', views.admin_edit_event, name="admin_edit_event"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/datasets$', views.admin_event_datasets, name="admin_event_datasets"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/add-dataset/$', views.admin_event_add_dataset, name="admin_event_add_dataset"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/(?P<dataset_id>[-\w]+)/$', views.admin_event_edit_dataset, name="admin_event_edit_dataset"),
    url(r'^admin/events/(?P<event_id>[-\w]+)/(?P<dataset_id>[-\w]+)/delete$', views.admin_event_delete_dataset, name="admin_event_delete_dataset"),
    url(r'^.*$', views.index, name='index'),

]

designsafe/urls.py
"""
DesignSafe-CI URL Configuration
===============================

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/

Examples:
---------

**Function views**

#. Add an import:  from my_app import views
#. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')

**Class-based views**

#. Add an import:  from other_app.views import Home
#. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
    
**Including another URLconf**

#. Add an import:  from blog import urls as blog_urls
#. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from designsafe.apps.auth.views import login_options as des_login_options
from django.contrib.auth.views import logout as des_logout
from designsafe.views import project_version as des_version

# sitemap - classes must be imported and added to sitemap dictionary
from django.contrib.sitemaps.views import sitemap
from cms.sitemaps import CMSSitemap
from designsafe.sitemaps import StaticViewSitemap, DynamicViewSitemap, HomeSitemap, ProjectSitemap, SubSitemap
from designsafe import views

# cms preferences
CMSSitemap.priority = 0.7
CMSSitemap.changefreq = 'weekly'

sitemaps = {
    'home': HomeSitemap,
    'subsite': SubSitemap,
    'static': StaticViewSitemap,
    'dynamic': DynamicViewSitemap,
    'projects': ProjectSitemap,
    'cmspages': CMSSitemap,
}

urlpatterns = [
    # admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/impersonate/', include('impersonate.urls')),

    # sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # terms-and-conditions
    url(r'^terms/', include('termsandconditions.urls')),

    url(r'^api/', include('designsafe.apps.api.urls', namespace='designsafe_api')),

    # RAMP verification
    url(r'{}.html$'.format(settings.RAMP_VERIFICATION_ID), TemplateView.as_view(template_name='ramp_verification.html')),
    
    # api urls, just for the samples.
    url(r'^applications/', include('designsafe.apps.applications.urls',
                                namespace='designsafe_applications')),
    url(r'^data/', include('designsafe.apps.data.urls', namespace='designsafe_data')),
    url(r'^rw/workspace/', include('designsafe.apps.workspace.urls',
                                   namespace='designsafe_workspace')),
    url(r'^notifications/', include('designsafe.apps.notifications.urls',
                                    namespace='designsafe_notifications')),
    url(r'^search/', include('designsafe.apps.search.urls',
                                    namespace='designsafe_search')),
    url(r'^geo/', include('designsafe.apps.geo.urls',
                                    namespace='designsafe_geo')),
    url(r'^recon-portal/', include('designsafe.apps.rapid.urls',
                                    namespace='designsafe_rapid')),


    # auth
    url(r'^account/', include('designsafe.apps.accounts.urls',
        namespace='designsafe_accounts')),
    url(r'^register/$', RedirectView.as_view(
        pattern_name='designsafe_accounts:register', permanent=True), name='register'),

    # dashboard
    url(r'^dashboard/', include('designsafe.apps.dashboard.urls',
        namespace='designsafe_dashboard')),

    # need a fancier redirect here to pass the code param along
    url(r'^activate/(?:(?P<code>.+)/)?$',
        lambda x, code: HttpResponseRedirect(
            reverse('designsafe_accounts:email_confirmation',
                    args=[code] if code else None)
        )),
    url(r'^password-reset/(?:(?P<code>.+)/)?$',
        lambda x, code: HttpResponseRedirect(
            reverse('designsafe_accounts:password_reset',
                    args=[code] if code else None)
        )),

    # box
    url(r'^account/applications/box/', include('designsafe.apps.box_integration.urls',
        namespace='box_integration')),

    # dropbox
    url(r'^account/applications/dropbox/', include('designsafe.apps.dropbox_integration.urls',
        namespace='dropbox_integration')),

    # googledrive
    url(r'^account/applications/googledrive/', include('designsafe.apps.googledrive_integration.urls',
        namespace='googledrive_integration')),

    # google site verification
    url(r'{}.html$'.format(settings.GOOGLE_SITE_VERIFICATION_ID), TemplateView.as_view(template_name='google_verification.html')),

    # auth
    url(r'^auth/', include('designsafe.apps.auth.urls', namespace='designsafe_auth')),

    url(r'^login/$', des_login_options, name='login'),
    url(r'^logout/$', des_logout,
        {'next_page': '/auth/logged-out/'}, name='logout'),

    # help
    url(r'^help/', include('designsafe.apps.djangoRT.urls', namespace='djangoRT')),

    # webhooks
    url(r'^webhooks/', include('designsafe.webhooks')),

    # version check
    url(r'^version/', des_version),

    # cms handles everything else
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),

]
if settings.DEBUG: 
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

designsafe/apps/accounts/models.py
from django.conf import settings
from django.db import models
from django.db import connections, DatabaseError
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
import logging
import six

logger = logging.getLogger(__name__)


class NEESUser(object):

    def __init__(self, **kwargs):
        for k, v in six.iteritems(kwargs):
            setattr(self, k, v)

    _lookup_sql = "SELECT u.username, u.email, p.givenName, p.middleName, p.surname, " \
                  "p.organization, p.countryresident, p.countryorigin, p.phone, " \
                  "a.address1, a.address2, a.addressCity, a.addressRegion, " \
                  "a.addressPosstal, a.addressCountry " \
                  "FROM jos_users u JOIN jos_xprofiles p ON p.uidNumber = u.id " \
                  "LEFT JOIN jos_xprofiles_address a ON a.uidNumber = u.id " \
                  "WHERE u.email = %s"

    @classmethod
    def lookup_user(cls, email):
        if 'nees_users' in connections:
            cursor = connections['nees_users'].cursor()
            try:
                cursor.execute(cls._lookup_sql, [email])
                columns = [col[0] for col in cursor.description]
                return [
                    cls(**dict(zip(columns, row)))
                    for row in cursor.fetchall()
                ]
            finally:
                cursor.close()
        else:
            logger.error('Database connection for `nees_users` is not defined')
            raise DatabaseError('The NEES users database connection is unavailable.')


class DesignSafeProfileNHInterests(models.Model):
    description = models.CharField(max_length=300)

    def __unicode__(self):
        return self.description


class DesignSafeProfileResearchActivities(models.Model):
    description = models.CharField(max_length=300)

    def __unicode__(self):
        return self.description


class DesignSafeProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')
    ethnicity = models.CharField(max_length=255)
    gender = models.CharField(max_length=255)
    agree_to_account_limit = models.DateTimeField(auto_now_add=True, null=True)
    bio = models.CharField(max_length=4096, default=None, null=True, blank=True)
    website = models.CharField(max_length=256, default=None, null=True, blank=True)
    orcid_id = models.CharField(max_length=256, default=None, null=True, blank=True)
    nh_interests = models.ManyToManyField(DesignSafeProfileNHInterests)
    professional_level = models.CharField(max_length=256, default=None, null=True)
    research_activities = models.ManyToManyField(DesignSafeProfileResearchActivities)

    def send_mail(self, subject, body=None):
        send_mail(subject,
                  body,
                  settings.DEFAULT_FROM_EMAIL,
                  [self.user.email],
                  html_message=body)

class NotificationPreferences(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='notification_preferences')
    announcements = models.BooleanField(
        default=True,
        verbose_name=_('Announcements: to communicate EF Workshops, NHERI Newsletter, Student Opportunities, etc.'))

    tutorials = models.BooleanField(
        default=True,
        verbose_name=_('Tutorials: to communicate DesignSafe training opportunities.'))

    designsafe = models.BooleanField(
        default=True,
        verbose_name=_('DesignSafe: to communicate new features, planned outages.'))

    class Meta:
        permissions = (
            ('view_notification_subscribers', 'Can view list of users subscribed to a '
                                              'notification type'),
        )

designsafe/apps/api/messages/models.py
from __future__ import unicode_literals
import logging
from django.db import models

logger = logging.getLogger(__name__)
TYPE_CHOICES = (
    ('alert-warning', 'WARNING'),
    ('alert-danger', 'DANGER'),
    ('alert-info', 'INFO'),
    ('alert-success', 'SUCCESS'),
    )

class PageAlert(models.Model):
    name = models.CharField(max_length=120, unique=True, primary_key=True)
    alert_type = models.CharField(max_length=20, choices=TYPE_CHOICES, default='alert-warning')
    message = models.TextField(help_text='Page alert message text.')
    is_active = models.BooleanField(default=False)
    
    def __str__(self):
        return '{name}: {alert_type} - {message}...'.format(
            name=self.name,
            alert_type=self.alert_type,
            message=self.message[0:50]
        )

    def __repr__(self):
        return {
            'name':self.name,
            'alert_type':self.alert_type,
            'message':self.message,
            'is_active':self.is_active
        }

designsafe/apps/api/models.py
from django.db import models

# Create your models here.
#from designsafe.apps.api.agave.models.fields import *
#from designsafe.apps.api.projects.models import *

#from designsafe.apps.api.agave.models.base import set_lazy_rels
#set_lazy_rels()

designsafe/apps/applications/models.py
from django.db import models

designsafe/apps/box_integration/models.py
from boxsdk import Client, OAuth2
from django.db import models
from django.conf import settings
import json


class BoxUserToken(models.Model):
    """
    Represents an OAuth Token for a Box.com user
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='box_user_token')
    box_user_id = models.CharField(max_length=48)
    access_token = models.CharField(max_length=255)
    refresh_token = models.CharField(max_length=255)

    def update_tokens(self, access_token, refresh_token):
        """
        Callable method that should be passed as the store_tokens callable
        for the BoxDSK OAuth2 object.

        Args:
            access_token: the updated access token
            refresh_token: the updated refresh token

        Returns:
            None
        """
        self.access_token = access_token
        self.refresh_token = refresh_token
        self.save()

    def get_token(self):
        """
        Convenience method to get current token.

        Returns:
            (access_token, refresh_token)

        """
        return self.access_token, self.refresh_token

    @property
    def client(self):
        oauth = OAuth2(client_id=settings.BOX_APP_CLIENT_ID,
                       client_secret=settings.BOX_APP_CLIENT_SECRET,
                       access_token=self.access_token,
                       refresh_token=self.refresh_token,
                       store_tokens=self.update_tokens)
        return Client(oauth)

designsafe/apps/cms_plugins/models.py
from django.db import models
from cms.models import CMSPlugin

class ResponsiveEmbedPlugin(CMSPlugin):
    url = models.CharField(max_length=255)
    aspect = models.CharField(max_length=255,
        choices=(("16by9","16by9"),("4by3","4by3"),("podcast","podcast")))
    allowfullscreen = models.BooleanField(verbose_name='Allow Fullscreen', default=True)

    def __unicode__(self):
        return self.url

designsafe/apps/data/models/taxonomy.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.validators import ASCIIUsernameValidator




class CustomUser(User):
    username_validator = ASCIIUsernameValidator()

class Vocab(models.Model):
    Term = models.CharField(max_length=40, unique=True)
    Definition = models.TextField(max_length=200)
    Source_of_Definition = models.UrlField(max_length=1000, unique=True)
    Date = DateTimeField(default=datetime.now(), auto_now_add=True)
    VocabBuilder = CustomUser()
    # Permalink = 

class Board(models.Model):
    display = models.CharField(max_length=30, unique=True)

designsafe/templates/includes/alerts.html
{% if request.session.alertslist_size > 0 %}
<div class="container ds-alert-container">
    {% for single_alert in request.session.alertslist %}
        {% if single_alert.is_active %}
            <div class="alert ds-alert {{ single_alert.alert_type }}">
                {% autoescape off %}{{ single_alert.message }}{% endautoescape %}
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}

designsafe/templates/includes/analytics.html
{% if GOOGLE_ANALYTICS_PROPERTY_ID %}
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', '{{ GOOGLE_ANALYTICS_PROPERTY_ID }}', 'auto');
ga('send', 'pageview');
</script>
{% endif %}

designsafe/templates/includes/cms_menu.html
{% load i18n menu_tags cache %}

{% for child in children %}
<li class="{% if child.ancestor or child.selected or request.get_full_path == child.url %}active{% endif %} {% if child.children %}dropdown{% endif %} {{child.attr.class}}">
    {% if child.children %}
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ child.get_menu_title | safe }} <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <!--
        <li {%if child.selected %}class="active"{% endif %}>
          <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title | safe }}</span></a>
        </li>
        -->
        {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
      </ul>
    {% else %}
      <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title | safe }}</span></a>
    {% endif %}
</li>
{% endfor %}

designsafe/templates/includes/ef_navigation.html
{% load menu_tags %}
<nav class="navbar navbar-default navbar-ds">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navigation" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navigation">
      <ul class="nav navbar-nav">
         {% show_menu 0 1 100 100 "includes/cms_menu.html" %}
      </ul>

    </div><!-- /.navbar-collapse -->
  </div>
</nav>

designsafe/templates/includes/footer.html
{% load staticfiles cms_tags %}
<footer class="container">
  <hr>
  <ul id="logos" class="list-unstyled">
    <li><img class="img-responsive nsflogo" src="{% static 'images/nsf.jpg' %}"></li>
  </ul>
  {% static_placeholder 'site_footer' site or %}
  <p class="text-center">
    DesignSafe-CI is supported by a grant from the National Science Foundation
    (<a target="_blank" href="http://www.nsf.gov/awardsearch/showAward?AWD_ID=1520817">#1520817</a>).
  </p>
  {% endstatic_placeholder %}
</footer>
<div id="toast-container"></div>

designsafe/templates/includes/global_nav.html
<li><a href="/">DesignSafe Home</a></li>
<li role="separator" class="divider"></li>
<li><a href="/community/">NHERI Community</a></li>
<li><a href="/rw/">Research Workbench</a></li>
<li><a href="/facilities/">NHERI Facilities</a></li>
<li><a href="/learning-center/">Learning Center</a></li>
<li role="separator" class="divider"></li>
<li><a href="/account/">My Account</a></li>
<li><a href="/help/">Help</a></li>
<li><a href="/contact/">Contact</a></li>
<li><a href="/about/">About</a></li>

designsafe/templates/includes/header.html
{% load staticfiles %}
{% load static %}
{% load auth_extras %}
<header class="container site-banner">
  <div class="site-banner-left">
    <a class="logo" href="/">
      <h1 class="sr-only">DesignSafe-CI: A Natural Hazards Engineering Research Infrastructure (NHERI)</h1>
      <img alt="DesignSafe-CI" src="{% static 'images/Designsafe-Logo-tagline.png' %}" width="100%">
    </a>
  </div>

  <div class="site-banner-right">
    <div class="user-menu">
      {% if user.is_authenticated %}
        <span style="vertical-align:middle">
          {% if not agave_ready %}
            &nbsp;
            <a class="text-danger" title="API Session Not Available. Click for details." href="{% url 'designsafe_auth:agave_session_error' %}"><i class="fa fa-exclamation-triangle"></i><span class="sr-only">API Session Not Available. Click for details.</span></a>
          {% endif %}
        </span>
        <span ng-controller="NotificationBadgeCtrl" id="id_user_notify" ng-include="'{% static 'scripts/notifications/html/badge.html' %}'">
        </span>
        <div class="btn-group">
          <a href="{% url 'designsafe_dashboard:index' %}" class="btn btn-link-alt">Welcome, {{ user.first_name }}!</a>
          <button type="button" class="btn btn-link-alt dropdown-toggle"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="{% url 'designsafe_dashboard:index' %}">My Dashboard</a></li>
            <li><a href="{% url 'designsafe_notifications:index' %}">Notifications</a></li>
            <li><a href="{% url 'djangoRT:mytickets' %}">My Tickets</a></li>
            {% if user|has_group:'Rapid Admin' %}
              <li><a href="{% url 'designsafe_rapid:admin'%}" target="_self"> Rapid Admin </a></li>
            {% endif %}
            <li><a href="{% url 'logout' %}">Log out</a></li>
            {% if user.is_impersonate %}
              <li><a href="{% url 'impersonate-stop' %}">Stop impersonating {{user}}</a></li>
            {% endif %}
          </ul>
        </div>

      {% else %}
      <div class="btn-group">
        <a href="{% url 'login' %}" class="btn btn-link-alt">Log in</a>
        <a href="{% url 'register' %}" class="btn btn-link-alt">Register</a>
      </div>
      {% endif %}
    </div>
  </div>
</header>

designsafe/templates/includes/homepage_navigation.html
<nav class="navbar navbar-default navbar-ds">
  <div class="container">
    <div class="navbar-header">
      <ul class="nav navbar-nav hidden-xs">
        <li>
          <button class="navbar-toggle" data-toggle="dropdown" aria-expanded="true" style="display:inherit">
            <span class="sr-only">Section navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <ul class="dropdown-menu">
            {% include 'includes/global_nav.html' %}
          </ul>
        </li>
      </ul>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navigation" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navigation">
      <ul class="nav navbar-nav">
        <li><a class="hover-text hl-community" href="/#community">NHERI Community</a></li>
        <li><a class="hover-text hl-research" href="/#research">Research Workbench</a></li>
        <li><a class="hover-text hl-ef" href="/#ef">Experimental Facilities</a></li>
        <li><a class="hover-text hl-learning" href="/#learning">Learning Center</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="{% if request.path == '/about/' %}active{% endif %}">
          <a href="/about">About</a>
        </li>
        <li class="{% if request.path == '/contact/' %}active{% endif %}">
          <a href="/contact">Contact</a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

designsafe/templates/includes/messages.html
{% if messages %}
  <div class="messages">
    <div class="container">
      {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <p>{{ message|safe }}</p>
      </div>
      {% endfor %}
    </div>
  </div>
{% endif %}
<div class="messages">
  <div class="container" id="agentMessage">
  </div>
</div>

designsafe/templates/includes/navigation.html
{% load menu_tags cms_tags %}
<nav class="navbar navbar-default navbar-ds">
  <div class="container">
    <div class="navbar-header">
      <ul class="nav navbar-nav hidden-xs">
        <li>
          <button class="navbar-toggle hidden-sm hidden-md hidden-lg" data-toggle="dropdown" aria-expanded="true" style="display:inherit">
            <span class="sr-only">Section navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <ul class="dropdown-menu">
            {% include 'includes/global_nav.html' %}
          </ul>
        </li>
      </ul>
      <!-- {% if section_root %}
        <a class="navbar-brand">{{section_root.title}}</a>
      {% endif %} -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navigation" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navigation">
      <ul class="nav navbar-nav">
         {% show_menu 1 2 100 100 "includes/cms_menu.html" %}
      </ul>
      <ul class="nav navbar-nav global-nav hidden-sm hidden-md hidden-lg">
        {% include 'includes/global_nav.html' %}
      </ul>
      <form class="navbar-form navbar-right">
        <input class="form-control" id="searchfield" placeholder="Search DesignSafe"><!--
     --><button class="btn btn-default" id="search_button"> <i class="fa fa-search"></i> </button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>